language: node_js
node_js:
  - "iojs"
  - "0.10"
  - "0.12"
os:
  - linux
  - osx
  - windows
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g coveralls
after_script:
  - npm run coverage
  - npm run coveralls
